packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^7.0.2
  '@types/node': ^26.2.0

allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  keytar: false
  puppeteer: false
  sharp: true
  workerd: false
